### ISSUE TITLE
Register with PyPI

### ISSUE THREAD

**Issue by daoudclarke** [datapastry/pypastry#5]
It would nice to be able to run `pip install pypastry` from anywhere.

**Comment by MrRutledge** [comment]
I've uploaded the PyPi package but I messed up the versions, I made a mistake and uploaded some zip/tar.zg files that I used while testing with TestPyPi. I deleted the version 0.0.2 from the [website.](https://pypi.org/project/pypastry/) It cautioned me before I took that action. On this [thread](https://github.com/pypa/packaging-problems/issues/74) they're saying it might cause some problems in future when we are uploading the v.0.0.2.

**Comment by daoudclarke** [comment]
Thanks for this! Good to know the above info, hopefully won't be a problem.

Fixed by #18

**Comment by daoudclarke** [comment]
Tested and confirmed this works (on a MacBook pro in a conda env).

**Comment by MrRutledge** [comment]
Hey, we get errors when we run `pastry run -m 'First experiment'`, it turns out this error affected the pypi version I uploaded last month. 
When you download the package and run it with the above command you get this error. 

**Tested locally** 
command: `pastry run -m 'first experiment'` 
*Output:*
`Traceback (most recent call last):
  File "/usr/local/bin/pastry", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/c/documents/github/pypastry/pastry", line 44, in <module>
    parse_and_run()
  File "/mnt/c/documents/github/pypastry/pastry", line 26, in parse_and_run
    from pypastry.commands.run import run

ImportError: No module named 'pypastry'`

**Tested on google collab we get**
command : `pastry init pastry-test`
*Output*
`Traceback (most recent call last):
  File "/usr/local/bin/pastry", line 44, in <module>
    parse_and_run()
  File "/usr/local/bin/pastry", line 29, in parse_and_run
    from pypastry.commands.init import run

ModuleNotFoundError: No module named 'pypastry'`

This happens when you use the pip install version from **Pypi** and the current  **git version on master** 

Solutions I have tried so far [StackOverflow](https://stackoverflow.com/questions/23417941/import-error-no-module-named-does-exist?noredirect=1&lq=1)

Should we reopen #5

**Comment by daoudclarke** [comment]
This sounds like a new issue, since it was working after your change - I'll create a new issue with the info you posted above.

**Comment by daoudclarke** [comment]
Hey @MrRutledge can you add me as a maintainer/owner on pypi?! My username is daoudc. Thanks!

**Comment by MrRutledge** [comment]
> daoudc

Forget the email I sent you I should've read this first. Yes sure I am going to add you.

**Comment by MrRutledge** [comment]
> Hey @MrRutledge can you add me as a maintainer/owner on pypi?! My username is daoudc. Thanks!

It's done!
